title: لینوکسی‌ها
email: linuxihaa@gmail.com
description: >
 سایت فارسی آموزش گنو/لینوکس و نرم‌افزارها و توزیع‌های لینوکس و اخبار مرتبط با آن‌ها
 هدف ما استفاده‌ی بهتر کاربران از توزیع‌های گنو/لینوکس است
short_description: وبسایت فارسی آموزش و اخبار گنو/لینوکس
baseurl: ""
url: http://linuxihaa.ir
twitter_username: linuxihaa
github_username:  linuxihaa
locale: fa_IR
lang: fa
direction: rtl

markdown: kramdown

encode: utf-8
timezone: Asian/Tehran
permalink: :title/

gems:
  - jekyll-paginate

paginate: 10
paginate_path: "page/:num/"

disqus_shortname: linuxihaa

imgurl: /assets/images
youtube: <div class='youtube'><iframe width='560' height='420' src='http://www.youtube.com/embed/ID?color=white&theme=light'></iframe></div>
anetwork: <script type="text/javascript"> ;!( function( w, d ) { 'use strict'; var ad = { user: "ID", width: 468, height: 60, id: 'anetwork-' + ~~( Math.random() * 999999 ) }, h = d.head || d.getElementsByTagName( 'head' )[ 0 ], s = location.protocol + '//static-cdn.anetwork.ir/aw/aw.js'; if ( typeof w.anetworkParams != 'object' ) w.anetworkParams = {}; d.write( '<div id="' + ad.id + '" style="display: inline-block"></div>' ); w.anetworkParams[ ad.id ] = ad; d.write( '<script type="text/javascript" src="' + s + '" async></scri' + 'pt>' ); })( this, document );</script>
